version: '3'

env:
  COMPOSE_FILE: .dev/compose.yaml

tasks:

  # dev environment

  dev:
    desc: Enter dev container.
    cmds:
      - task: dev:build
      - docker compose run --service-ports --rm dev

  dev:build:
    internal: true
    sources:
      - .dev/*
    cmds:
      - docker compose build

  # dev commands

  install:
    desc: Install package system-wide.
    cmds:
      - uv pip install --system -e .

  lint:
    desc: Run linters.
    cmds:
      - mypy src
      - ruff check
      - ruff format --check

  format:
    desc: Run code formatters.
    cmds:
      - ruff format

  version:
    desc: Bump project version. Use task version -- patch|minor|major|...
    cmds:
      - bump-my-version bump {{.CLI_ARGS}}

  release:
    desc: Publish package on PyPi.
    preconditions:
      - test $(git rev-parse --abbrev-ref HEAD) = main
    cmds:
      - rm -rf dist
      - uv build
      - uv publish

  # dev testing

  test:
    desc: Run tests.
    cmds:
      - tox run

  test:main:
    desc: Run tests in main environment.
    cmds:
      - tox run -m main

  test:debug:
    desc: Run tests and open debugger on errors.
    deps: [install]
    cmds:
      - pytest --pdb {{.CLI_ARGS}}
