[window]
decorations = "Buttonless"
dynamic_title = false
dimensions = { columns = 120, lines = 120 }
position = { x = 0, y = 0 }
padding = { x = 10, y = 10 }
opacity = 0.9

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 12
